rwbox.is-an.app
tarampampam/free-domains pull request #10
Opened 2022-11-12 11:05 UTC by ourstorycomic

### Link to Website

Link: https://ourstorycomic.github.io/rw-box

2022-11-12 11:12 UTC, tarampampam requested changes

2022-11-12 11:12 UTC, tarampampam commented on domains/rwbox.is-an.app.json
> +    "CNAME": "https://ourstorycomic.github.io/rw-box",
```suggestion
    "CNAME": "hourstorycomic.github.io.",
```

2022-11-12 11:28 UTC, tarampampam commented on domains/rwbox.is-an.app.json
> +    "CNAME": "https://ourstorycomic.github.io/rw-box",
ping @ourstorycomic

2022-11-12 13:08 UTC, tarampampam commented on domains/rwbox.is-an.app.json
> +    "gmail": "kaz442197@gmail.com"
```suggestion
    "email": "kaz442197@gmail.com"
```

2022-11-12 13:11 UTC, tarampampam commented on domains/rwbox.is-an.app.json
> +    "CNAME": "hourstorycomic.github.io.",
```suggestion
    "CNAME": "hourstorycomic.github.io."
```

2022-11-12 13:12 UTC, tarampampam approved these changes

2022-11-12 13:12 UTC, merged

2022-11-12 13:14 UTC, tarampampam commented
Done:

```
$ dig @1.1.1.1 +noall +answer rwbox.is-an.app
rwbox.is-an.app.	246	IN	CNAME	hourstorycomic.github.io.
hourstorycomic.github.io. 3546	IN	A	185.199.109.153
hourstorycomic.github.io. 3546	IN	A	185.199.110.153
hourstorycomic.github.io. 3546	IN	A	185.199.108.153
hourstorycomic.github.io. 3546	IN	A	185.199.111.153
```

2022-11-14 16:02 UTC, ourstorycomic commented
no actually it's not "hourstorycomic.github.io." lmfao, it's "ourstorycomic.github.io."

2022-11-14 16:05 UTC, tarampampam commented
Make a new PR with all required changes, please

2022-11-14 16:05 UTC, tarampampam commented
Oh, it was my mistake, one second

2022-11-14 16:07 UTC, tarampampam commented
Updated:

```
$ dig @1.1.1.1 +noall +answer rwbox.is-an.app
rwbox.is-an.app.	300	IN	CNAME	ourstorycomic.github.io.
ourstorycomic.github.io. 3600	IN	A	185.199.110.153
ourstorycomic.github.io. 3600	IN	A	185.199.111.153
ourstorycomic.github.io. 3600	IN	A	185.199.109.153
ourstorycomic.github.io. 3600	IN	A	185.199.108.153
```