Create survival2d.is-an.app
tarampampam/free-domains pull request #13
Opened 2022-11-16 14:58 UTC by tiennm99

Add CNAME to my current personal blog

### Plan
I make it for my project in school, but current it have not done yet. So I make a CNAME point to my personal blog as a holder

### Link to Website

Link: https://miti99.eu.org

2022-11-16 16:17 UTC, tarampampam commented
Wrong file name, add the `.json` at the end, please

2022-11-16 16:17 UTC, tarampampam commented on survival2d.is-an.app
> +    "CNAME": "miti99.eu.org"
```suggestion
    "CNAME": "miti99.eu.org."
```

2022-11-16 20:29 UTC, tarampampam requested changes
Change file extension

2022-11-17 02:44 UTC, tarampampam requested changes
The old file is not needed, right?

2022-11-17 02:46 UTC, tiennm99 commented
> The old file is not needed, right?

Yes, I don't see it in my branch so I add new file instead

2022-11-17 02:49 UTC, tarampampam commented
Take a look into the repository root directory

2022-11-17 02:51 UTC, tiennm99 commented
> Take a look into the repository root directory

Okay, I see & delete it. Thank you

2022-11-17 02:53 UTC, tarampampam requested changes
The subdomain and filename did not match

2022-11-17 03:05 UTC, tarampampam approved these changes

2022-11-17 03:05 UTC, merged