Add .is-an.app.js File
tarampampam/free-domains pull request #269
Opened 2023-04-21 09:05 UTC by Bhavesh-p-Patel

### Link to Website

Link: 

---

- [ ] Toggle this checkbox to re-run the stargazer checking

2023-04-21 09:24 UTC, tarampampam requested changes

2023-04-21 09:24 UTC, tarampampam commented on domains/Bhavase-p-Patel.is-an.app.js
Filename in lowercase, please

2023-04-21 09:24 UTC, tarampampam commented on domains/Bhavase-p-Patel.is-an.app.js
> +    subdomain: 'Bhavesh-p-Patel',
In lowercase, please

2023-04-21 09:24 UTC, tarampampam commented on domains/Bhavase-p-Patel.is-an.app.js
> +      CNAME: 'Bhavesh-p-Patel.github.io',
In lowercase, please

2023-04-21 11:23 UTC, tarampampam commented
@Bhavesh-p-Patel How many domains do you plan to register else?

2023-04-21 13:17 UTC, tarampampam approved these changes

2023-04-26 05:05 UTC, tarampampam commented
Closed due inactivity

2023-04-26 05:05 UTC, closed without merging

2023-04-27 12:46 UTC, soni-ashish commented
Give me proper reason to fix it @tarampampam

2023-04-27 12:53 UTC, tarampampam commented
I mean if your company wants to publicize its developer profiles, why not do that using the company domain name? Now it looks like a mass subdomain registration, that takes a lot of my time and interferes with my offline work.

That's why I asked - "How many sub-domains do you plan to register?". Without the answer and explanation, I will not register one more.