Update shredmod.is-an.app.json
tarampampam/free-domains pull request #77
Opened 2023-01-22 16:59 UTC by familycomicsstudios

### Pulling my new changes.

---

- [x] Toggle this checkbox to re-run the stargazer checking

2023-01-22 21:35 UTC, tarampampam requested changes

2023-01-22 21:35 UTC, tarampampam commented on domains/shredmod.is-an.app.json
> +    }
```suggestion
  },
  "nested": [
    {
      "subdomain": "packager",
      "record": {
        "CNAME": "shredmod.github.io"
      }
    },
    {
      "subdomain": "extensions",
      "record": {
        "CNAME": "shredmod.github.io"
      }
    },
    {
      "subdomain": "docs",
      "record": {
        "CNAME": "shredmod.github.io"
      }
    }
  ]
```

2023-01-22 21:47 UTC, tarampampam commented on domains/shredmod.is-an.app.json
> +      "subdomain": "docs",
```suggestion
      "subdomain": "documentations",
```

2023-01-22 21:48 UTC, tarampampam approved these changes

2023-01-22 21:49 UTC, tarampampam commented
Check now, please

2023-01-22 23:56 UTC, familycomicsstudios commented
Forgot to pull.

2023-01-23 05:57 UTC, tarampampam commented
Check the changes that I made

2023-01-23 12:27 UTC, familycomicsstudios commented
> Check the changes that I made

You can merge this now!

2023-01-23 14:08 UTC, merged