Add KrazyKleb Domain
tarampampam/free-domains pull request #87
Opened 2023-02-02 11:54 UTC by KrazyKleb999

For my "Portfolio"

### Link to Website

Link: portfoilio-production-2a0f.up.railway.app

---

- [ ] Toggle this checkbox to re-run the stargazer checking

2023-02-02 12:40 UTC, tarampampam requested changes

2023-02-02 12:40 UTC, tarampampam commented on domains/KrazyKleb.is-an.app.json
> +	"owner": {
In lower case, please

2023-02-02 12:40 UTC, tarampampam commented on domains/KrazyKleb.is-an.app.json
> +{
File name in lower case, please

2023-02-02 12:59 UTC, tarampampam requested changes

2023-02-02 12:59 UTC, tarampampam commented on domains/KrazyKleb.is-an.app.json
> +	"$schema": "../schemas/domain.schema.json",
indent size - 2 spaces (everywhere)

2023-02-02 22:08 UTC, KrazyKleb999 commented on domains/KrazyKleb.is-an.app.json
> +	"owner": {
Done!

2023-02-02 22:08 UTC, KrazyKleb999 commented on domains/KrazyKleb.is-an.app.json
> +{
Done!

2023-02-03 05:05 UTC, tarampampam commented on domains/KrazyKleb.is-an.app.json
> +{
Nope :(

2023-02-06 07:07 UTC, tarampampam commented
closed due inactivity

2023-02-06 07:07 UTC, closed without merging